"""Koda's retrieval and context core."""

from __future__ import annotations

from .agent import ROLE_PROMPT, open_session, run_turn
from .budget import ContextBudget, TokenCalibrator, allocate
from .config import CoreConfig, config_defaults, merge_config
from .constants import CHARS_PER_TOKEN
from .context import Bootstrap, TurnBoundaries, begin_turn, build_context, rebase, safe_cut_index
from .contracts import (
    BlobRef,
    CachePlan,
    Chunk,
    CoChangeMemory,
    Definition,
    Escalation,
    FileAnalysis,
    FileRanks,
    Formulation,
    Formulator,
    Hit,
    Ledger,
    LedgerEntry,
    MirrorSet,
    ModelRequest,
    ModelTurn,
    Overlay,
    Reference,
    RepoMap,
    RepoMemory,
    RepositoryIndex,
    Rewrite,
    SearchResult,
    Session,
    SessionContext,
    SideUsage,
    SkippedFile,
    SourceFile,
    Span,
    ToolCall,
    ToolHost,
    ToolOutcome,
    Transcript,
    TurnResult,
    TurnUsage,
    UtilityModel,
    WorkingSet,
    iter_chunks,
    iter_indexable_chunks,
)
from .elide import compact, hot_cold
from .errors import (
    CacheError,
    ConfigError,
    CoreError,
    ParseError,
    RedactedFileError,
    WorkspaceError,
)
from .escalate import FormulationCache, escalated_search
from .fold import SessionState, fold_turn
from .graph import CodeGraph, build_graph, pagerank
from .ledger import distil_into, record, record_read, rehydrate, render_ledger
from .loop import TurnMeters
from .prompt import assemble, build_prefix
from .repomap import MapBuild, build_map
from .retrieval import Retriever, build_retriever, search
from .tokens import estimate_tokens
from .tools import TOOL_NAMES
from .tools.run import NullHost, run_tool
from .workingset import working_set_for
from .workspace import LocalWorkspace, MemoryWorkspace, Workspace, text_workspace

__all__ = [
    "BlobRef",
    "Block",
    "Bootstrap",
    "CHARS_PER_TOKEN",
    "CacheError",
    "CachePlan",
    "ChatModel",
    "Chunk",
    "CoChangeMemory",
    "CodeGraph",
    "Completion",
    "ConfigError",
    "ContextBudget",
    "CoreConfig",
    "CoreError",
    "Definition",
    "Escalation",
    "FileAnalysis",
    "FileRanks",
    "Formulation",
    "FormulationCache",
    "Formulator",
    "Hit",
    "Ledger",
    "LedgerEntry",
    "LocalWorkspace",
    "MapBuild",
    "MemoryWorkspace",
    "MirrorSet",
    "ModelRequest",
    "ModelTurn",
    "NullHost",
    "Overlay",
    "ParseError",
    "ROLE_PROMPT",
    "RedactedFileError",
    "Reference",
    "RepoMap",
    "RepoMemory",
    "RepositoryIndex",
    "Retriever",
    "Rewrite",
    "SearchResult",
    "Session",
    "SessionContext",
    "SessionState",
    "SideUsage",
    "SkippedFile",
    "SourceFile",
    "Span",
    "TOOL_NAMES",
    "TokenCalibrator",
    "ToolCall",
    "ToolHost",
    "ToolOutcome",
    "Transcript",
    "TurnBoundaries",
    "TurnMeters",
    "TurnResult",
    "TurnUsage",
    "UtilityModel",
    "WorkingSet",
    "Workspace",
    "WorkspaceError",
    "allocate",
    "assemble",
    "begin_turn",
    "build_context",
    "build_graph",
    "build_map",
    "build_prefix",
    "build_retriever",
    "compact",
    "config_defaults",
    "distil_into",
    "escalated_search",
    "estimate_tokens",
    "fold_turn",
    "hot_cold",
    "iter_chunks",
    "iter_indexable_chunks",
    "merge_config",
    "open_session",
    "pagerank",
    "rebase",
    "record",
    "record_read",
    "rehydrate",
    "render_ledger",
    "run_tool",
    "run_turn",
    "safe_cut_index",
    "search",
    "text_workspace",
    "working_set_for",
]
