"""Data shapes only. No I/O, no policy, no behaviour beyond validation."""

from __future__ import annotations

from .agent import (
    ChatModel,
    ModelRequest,
    ModelTurn,
    Session,
    ToolCall,
    ToolHost,
    ToolOutcome,
    TurnResult,
    TurnUsage,
)
from .analysis import FileAnalysis, SkippedFile, SkipReason
from .chunks import Chunk, ChunkKind, is_indexable_role
from .escalation import (
    Escalation,
    FanoutAngle,
    Formulation,
    Formulator,
    Rewrite,
    Rung,
    SideUsage,
)
from .ledger import (
    LEDGER_KINDS,
    BlobRef,
    Confidence,
    Ledger,
    LedgerEntry,
    LedgerKind,
    LedgerSource,
)
from .model import Completion, UtilityModel
from .prompt import (
    CachePlan,
    CacheTtl,
    Message,
    ModelCacheLimits,
    PromptBlock,
    PromptBudget,
    TranscriptMarker,
)
from .repo_map import FileRanks, MirrorSet, RepoMap
from .repository import (
    RepositoryIndex,
    chunk_by_digest,
    definitions_by_name,
    files_referencing,
    iter_chunks,
    iter_definitions,
    iter_indexable_chunks,
    with_file,
    with_skip,
    without_file,
)
from .retrieval import LEG_TRUST, UNKNOWN_LEG_TRUST, Hit, LegName, LegResult, SearchResult
from .session import CoChangeMemory, RepoMemory, SessionContext
from .source import FileStat, Overlay, SourceFile, Span
from .symbols import (
    REFERENCE_KINDS,
    SYMBOL_ROLES,
    Definition,
    DefinitionSite,
    ParseResult,
    Reference,
    ReferenceKind,
    SymbolRole,
)
from .transcript import Block, BlockKind, Transcript, transcript_of
from .working_set import WorkingSet, WorkingSpan

__all__ = [
    "BlobRef",
    "Block",
    "BlockKind",
    "CachePlan",
    "CacheTtl",
    "ChatModel",
    "Chunk",
    "ChunkKind",
    "CoChangeMemory",
    "Completion",
    "Confidence",
    "Definition",
    "DefinitionSite",
    "Escalation",
    "FanoutAngle",
    "FileAnalysis",
    "FileRanks",
    "FileStat",
    "Formulation",
    "Formulator",
    "Hit",
    "LEDGER_KINDS",
    "LEG_TRUST",
    "Ledger",
    "LedgerEntry",
    "LedgerKind",
    "LedgerSource",
    "LegName",
    "LegResult",
    "Message",
    "MirrorSet",
    "ModelCacheLimits",
    "ModelRequest",
    "ModelTurn",
    "Overlay",
    "ParseResult",
    "PromptBlock",
    "PromptBudget",
    "REFERENCE_KINDS",
    "Reference",
    "ReferenceKind",
    "RepoMap",
    "RepoMemory",
    "RepositoryIndex",
    "Rewrite",
    "Rung",
    "SYMBOL_ROLES",
    "SearchResult",
    "Session",
    "SessionContext",
    "SideUsage",
    "SkipReason",
    "SkippedFile",
    "SourceFile",
    "Span",
    "SymbolRole",
    "ToolCall",
    "ToolHost",
    "ToolOutcome",
    "Transcript",
    "TranscriptMarker",
    "TurnResult",
    "TurnUsage",
    "UNKNOWN_LEG_TRUST",
    "UtilityModel",
    "WorkingSet",
    "WorkingSpan",
    "chunk_by_digest",
    "definitions_by_name",
    "files_referencing",
    "is_indexable_role",
    "iter_chunks",
    "iter_definitions",
    "iter_indexable_chunks",
    "transcript_of",
    "with_file",
    "with_skip",
    "without_file",
]
